# Generated by Django 5.0.7 on 2024-07-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='descripton',
            new_name='description',
        ),
    ]
